# Automatically updated by the winget bot at 2021/Feb/24
Id: Heroku.HerokuCLI
Version: 7.49.0.0
Name: HerokuCLI
AppMoniker: heroku
Publisher: Heroku
License: ISC License
LicenseUrl: https://github.com/heroku/cli/blob/master/LICENSE
Description: The Heroku Command Line Interface (CLI) makes it easy to create and manage your Heroku apps directly from the terminal. It is an essential part of using Heroku.
Homepage: https://devcenter.heroku.com/articles/heroku-cli
Installers:
- Arch: x64
  Url: https://cli-assets.heroku.com/heroku-x64.exe
  Sha256: 5E4BEEA52E08F2CF8B0CDB0A4A3F7A2EC70085FFF0D1B03AB71651B391E3BE0E
  InstallerType: nullsoft
